name: lumina_clock
description: A classy, neumorphic clock and productivity app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_neumorphic_plus: ^3.1.0
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  # Logic & Utilities
  intl: ^0.19.0
  provider: ^6.1.1
  # Hardware Featuresflutter pub get

  
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Icon & Splash Generators
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

# Configuration: App Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

# Configuration: Splash Screen
flutter_native_splash:
  color: "#E0E5EC"
  image: "assets/icon.png"
  fullscreen: true
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  
  # This tells Flutter to bundle your images
  assets:
    - assets/
    - assets/sounds/